---

- name: Create Server Container
  local_action:
    module: community.general.docker_container
    name: "{{ ansible_host }}"
    hostname: "{{ ansible_host }}"
    image: "{{ devshop_host_docker_image }}"
    command: "{{ devshop_host_docker_command | default(omit)}}"
    published_ports: "{{ devshop_host_docker_published_ports | default(omit)}}"
    volumes: "{{ devshop_host_docker_volumes | default(omit)}}"
    privileged: "{{ devshop_host_docker_privileged | default(omit)}}"
    working_dir: "{{ devshop_host_docker_working_dir | default(devshop_platform_user_home)}}"
    labels: "{{ devshop_host_docker_labels | default(omit) }}"

  run_once: True
  when:
    - devshop_host_type is defined
    - devshop_host_type == "docker"
    - ansible_connection == "docker"
