---

# @TODO: For all app hosts using this container:
# - Add to devshop_host_docker_volumes
# - Add labels for traefik:
#   traefik.http.routers.apphostlocalcomputer.rule: "Host(`apphost.local.computer`)"

- name: Prepare container vars from Apps
  with_items: "{{ groups['apps'] }}"
  delegate_to: "{{ item }}"
  set_fact:
#    devshop_host_docker_volumes: "{{ devshop_host_docker_volumes + [hostvars[item]['devshop_app_git_root'] + ':' + hostvars[item]['devshop_app_git_root']] }}"
    devshop_host_docker_labels: "{{ devshop_host_docker_labels | default({}) | combine({'traefik.http.routers.vhosts.rule': 'Host(`' + item + '`)'}) }}"
  when:
    - hostvars[item]['devshop_app_host'] == inventory_hostname
    - devshop_host_type is defined
    - devshop_host_type == "docker"
    - ansible_connection == "docker"

- name: Create Server Container
  local_action:
    module: community.general.docker_container
    name: "{{ inventory_hostname }}"
    hostname: "{{ inventory_hostname }}"
    image: "{{ devshop_host_docker_image }}"
    command: "{{ devshop_host_docker_command | default(omit)}}"
    published_ports: "{{ devshop_host_docker_published_ports | default(omit)}}"
    volumes: "{{ devshop_host_docker_volumes | default(omit)}}"
    privileged: "{{ devshop_host_docker_privileged | default(omit)}}"
    working_dir: "{{ devshop_host_docker_working_dir | default(devshop_platform_user_home)}}"
    labels: "{{ devshop_host_docker_labels | default(omit) }}"

  run_once: True
  when:
    - devshop_host_type is defined
    - devshop_host_type == "docker"
    - ansible_connection == "docker"
