---
#
# devshop.platform.playbook
#
# Global playbook for a devshop platform.
#
# Import this playbook in your own playbook in your own platform codebase.
# Optionally, set vars in the task or include a vars file by setting 'platform_vars_file'
#
# - name: Import the DevShop.Platform Playbook.
#   import_playbook: roles/contrib/ansible_collections/devshop/platform/playbook.yml
#
#   vars:
#    platform_vars_file: "vars.yml" # Path relative to this playbook file.
#

- name: Servers
  collections:
    - devshop.platform

  hosts: servers
  become: yes
  gather_facts: yes
  tags:
    - servers

  pre_tasks:
    - name: Include platform vars file from importing playbook.
      include_vars: "{{ lookup('env', 'PWD') }}/{{ platform_vars_file }}"
      when: platform_vars_file is defined

  roles:
    - role: host
      tags:
        - servers

    - role: services
      tags:
        - services

- name: Apps
  hosts: apps
  become: yes
  gather_facts: no

  tags:
    - apps

  pre_tasks:

    - name: Gather Server Facts
      server_facts:
        name: whatever
      register: server_facts_register

    - name: Define App Servers
      set_fact:
        devshop_app_servers: "{{ server_facts_register.server_facts }}"

    - name: Include platform vars file from importing playbook.
      include_vars: "{{ lookup('env', 'PWD') }}/{{ platform_vars_file }}"
      when: platform_vars_file is defined

  roles:
    - name: app
      delegate_to: "{{ devshop_app_host }}"
