---

- name: Run a command with piping.
  hosts: localhost
  gather_facts: no
  tasks:
    - command:
        cmd: "bash print-err-out.sh"
        stdout_file: ping.log
        stderr_file: ping.bad.log
        stdout_pipe: ">"
        stderr_pipe: ">"
