---
# The user to clone code and run commands with.
devshop_app_user: "platform"
devshop_app_user_group: "{{ devshop_app_user }}"

# The path to clone the "devshop_app_git_repository" to.
devshop_host_apps_root: "/var/platform"
devshop_app_git_root: "{{ devshop_host_apps_root }}/apps/{{ inventory_hostname }}"

# The git remote to clone.
devshop_app_git_repository: "http://github.com/opendevshop/devshop-control-template.git"

# The git reference to check out. (optional. If left blank, git repository default branch will be used.)
devshop_app_git_reference: ""

# Whether the git checkout should be forced. If set to true, any local modifications to files will be lost.
devshop_app_git_force: true

# Passed to ansible.builtin.git recursive option.
# Set to false to stop git from cloning the repo with the "recursive" option.
devshop_app_git_recursive: true

# Passed to ansible.builtin.git track_submodules option.
# Set to true to check out submodules on their specified branch.
devshop_app_git_track_submodules: false

# Notify git handlers even if git repo did not change.
force_build: false

# Tell the app what to do when running the app playbook.
# Override in your inventory or playbook extra vars.
devshop_app_playbook_stages:
  - build
  - install
  - deploy
  - test

# Tell the playbook to skip these stages.
skip_stages: []
