---
# The user to clone code and run commands with.
devshop_app_user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER, true) | default(ansible_user_id, true) }}"

# The path to clone the "devshop_app_git_repository" to.
devshop_host_apps_root: "/var/platform"
devshop_app_git_root: "{{ devshop_host_apps_root }}/apps/{{ inventory_hostname }}"

# The git remote to clone.
devshop_app_git_repository: "http://github.com/opendevshop/devshop-control-template.git"

# The git reference to check out. (optional. If left blank, git repository default branch will be used.)
devshop_app_git_reference: ""

# Notify git handlers even if git repo did not change.
devshop_app_force_git_handlers: false