---
apache_vhosts: []

devshop_service_http_apache_mods_enabled:
    - expires.load
    - ssl.load
    - rewrite.load
    - proxy.load
    - proxy_fcgi.load

# Override with app.document_root or env.document_root

devshop_service_http_document_root: "web"
devshop_host_apps_root: "/var/platform"
devshop_app_git_root: "{{ devshop_host_apps_root }}/apps/{{ inventory_hostname }}"