---
- name: "Hi App Host"
  debug:
    msg: "{{ devshop_app_hostname }}"

- set_fact:
    apache_vhosts: []

- name: "Gather Vhosts"
  loop: "{{ devshop_app_host['devshop_app_data']['environments'] | list }}"
  set_fact:
    apache_vhosts: "{{ apache_vhosts + [{
        'servername': devshop_app_hostname,
        'documentroot': devshop_app_source_path + '/' + devshop_app_source_docroot,
        'serveralias': devshop_app_environment.domains | default([])

    }] }}"
  vars:
    apache_vhosts: []

- name: "Vhosts Set!"
  debug:
    msg: "{{ apache_vhosts | to_nice_yaml }}"
