---
- name: "Welcome to the DevShop.App role: Drupal."
  debug:
    msg: |
      inventory_hostname: {{ inventory_hostname }}"

- name: Check if site is already installed.
  command:
    cmd: "drush status --root={{ devshop_app_git_root }}"
    chdir: "{{ devshop_app_git_root }}"
  register: drupal_status_register
  failed_when: "drupal_status_register.stdout is undefined"
  changed_when: false
  become: yes
  become_user: "{{ devshop_app_user }}"

- set_fact:
    devshop_app_installed: "{{ 'Drupal bootstrap' in drupal_status_register.stdout }}"
    devshop_app_drush_status: "{{ drupal_status_register.stdout }}"

- name: Save settings.php file
  template:
    src: "{{ devshop_app_drupal_settings_include_template }}"
    dest: "{{ devshop_app_git_document_root_path }}/{{ devshop_app_drupal_settings_site_folder }}/{{ devshop_app_drupal_settings_include_filename }}"
  when: devshop_app_drupal_create_settings_file | bool


- name: "Drupal App Role complete."
  debug:
    msg: |
      Site Installed: {{ devshop_app_installed }}

      Drush Status:
      {{ devshop_app_drush_status }}
