---
- name: "Welcome to the DevShop.App role: Drupal."
  debug:
    msg: |
      inventory_hostname: {{ inventory_hostname }}"

- name: Check if site is already installed.
  command: "{{ drush_path }} --root={{ drupal_core_path }} status bootstrap"
  args:
    chdir: "{{ drupal_core_path }}"
  register: drupal_site_installed
  failed_when: "drupal_site_installed.stdout is undefined"
  changed_when: false
  become: false

- name: Add install to skipped_stages unless force_install is set.
  set_fact:
    skip_stages: "{{ skip_stages + ['install']}}"
  when:
    - force_install is not defined or force_install == false