---
- name: Prepare .env file.
  file:
    path: "{{ devshop_app_env_file_path }}"
    state: touch

- name: Write service variables to .env file.
  blockinfile:
    path: "{{ devshop_app_env_file_path }}"
    block: |
      ##
      ## Written by opendevshop/devshop.platform:roles/app/tasks/drupal.post-git.yml
      ##
      ##
      MYSQL_DATABASE={{ devshop_service_db_name }}
      MYSQL_USER={{ devshop_service_db_user }}
      MYSQL_PASSWORD={{ devshop_service_db_password }}
      MYSQL_HOSTNAME={{ devshop_service_db_host }}
      MYSQL_PORT={{ devshop_service_db_port }}
      ## END ansible_managed.

  when:
    - devshop_service_db_name | default(false)

#
#- name: Make sure settings folder exists
#  file:
#    state: directory
#    recurse: yes
#    path: "{{ devshop_app_git_document_root_path }}/{{ devshop_app_drupal_settings_site_folder }}"
#
#- name: Save settings.devshop.php file
#  template:
#    src: "{{ devshop_app_drupal_settings_include_template }}"
#    dest: "{{ devshop_app_git_document_root_path }}/{{ devshop_app_drupal_settings_site_folder }}/{{ devshop_app_drupal_settings_include_filename }}"
#    owner: "{{ devshop_app_user }}"
#    group: "{{ devshop_app_user_group | default(devshop_app_user) }}"
#    mode: '0664'
#  when:
#  - devshop_app_drupal_create_settings_file | bool
#  - devshop_service_db_name | default(false)
#
#- name: Include settings.devshop.php file
#  blockinfile:
#    path: "{{ devshop_app_git_document_root_path }}/{{ devshop_app_drupal_settings_site_folder }}/{{ devshop_app_drupal_settings_php_filename }}"
#    block: "{{ devshop_app_drupal_settings_include_code }}"
#  when:
#    - devshop_app_drupal_create_settings_file | bool
#    - devshop_service_db_name | default(false)
