---
- name: "Welcome to the DevShop.App role: Drupal."
  debug:
    msg: |
      inventory_hostname: {{ inventory_hostname }}"

- name: Check if site is already installed.
  command:
    cmd: "drush --root={{ devshop_app_git_document_root_path }} status bootstrap"
    chdir: "{{ devshop_app_git_document_root_path }}"
  register: drupal_status_register
  failed_when: "drupal_status_register.stdout is undefined"
  changed_when: false
  become: yes
  become_user: "{{ devshop_app_user }}"

- set_fact:
    devshop_app_installed: "{{ 'Drupal bootstrap' in drupal_status_register.stdout }}"
    devshop_app_drush_status: "{{ drupal_status_register.stdout }}"

- name: "Drupal App Role complete."
  debug:
    msg: |
      Site Installed: {{ devshop_app_installed }}

      Drush Status:
      {{ devshop_app_drush_status }}
