---

- name: Prepare command logs directory
  file:
    path: "{{ devshop_app_commands_log_file | dirname }}"
    state: directory
    owner: "{{ devshop_app_commands_log_file_owner }}"
    group: "{{ devshop_app_commands_log_file_group }}"
    mode: "{{ devshop_app_commands_log_file_mode }}"

- name: Remove command logs file.
  file:
    path: "{{ devshop_app_commands_log_file }}"
    state: absent
  when: devshop_app_command_log_file_delete_before_start

- name: Run DevShop App command stages.
  loop: "{{ devshop_app_playbook_stages }}"
  loop_control:
    loop_var: stage
  command:
    cmd: "{{ lookup('vars', 'devshop_app_command_' + stage) }}"
    chdir: "{{ devshop_app_git_root }}"
    stdout_file: "{{ devshop_app_commands_log_file }}"
    stdout_pipe: ">>"
    stderr_file: "{{ devshop_app_commands_log_file }}"
    stderr_pipe: ">>"
  become: yes
  become_user: "{{ devshop_app_user }}"
  when:
    - lookup('vars', 'devshop_app_command_' + stage)
    - stage not in skip_stages | list | join
  register: devshop_app_playbook_stage_register
  ignore_errors: "{{ devshop_app_commands_ignore_errors }}"
  environment: "{{ devshop_app_shell_environment | combine(devshop_app_shell_environment_extra ) }}"

- name: DevShop.App Command Stages Complete.
  debug:
    var: "{{ devshop_app_playbook_stage_register }}"
