---

- name: Run DevShop App command stages.
  loop: "{{ devshop_app_playbook_stages }}"
  loop_control:
    loop_var: stage
  shell:
    cmd: "{{ lookup('vars', 'devshop_app_command_' + stage) }} 2>&1"
    chdir: "{{ devshop_app_git_root }}"
  become: yes
  become_user: "{{ devshop_app_user }}"
  when:
    - lookup('vars', 'devshop_app_command_' + stage)
    - stage not in skip_stages | list | join
  register: devshop_app_playbook_stage_register
  ignore_errors: "{{ devshop_app_commands_fail_playbook }}"
  environment: "{{ devshop_app_shell_environment | combine(devshop_app_shell_environment_extra ) }}"
