---
- name: Gather App Host facts.
  gather_facts:

- name: Prevent the role from running as root.
  fail:
    msg: "The devshop.app role should not be run as root."
  when: devshop_app_user == 'root'

- name: DevShop.App Role
  debug:
    msg: |
      ---------------------------------
      Welcome to the DevShop.App role.
      ---------------------------------
      http://{{ inventory_hostname }}
      devshop_app_git_repository: {{ devshop_app_git_repository }}
      devshop_app_git_reference: {{ devshop_app_git_reference }}
      devshop_app_git_root: {{ devshop_app_git_root }}
      ---------------------------------
      devshop_app_user: {{ devshop_app_user }}

      devshop_app_host: {{ devshop_app_server_http }}
      devshop_app_server_http: {{ devshop_app_server_http }}
      devshop_app_server_db: {{ devshop_app_server_db }}

      devshop_app_command_build: {{ devshop_app_command_build }}
      devshop_app_command_deploy: {{ devshop_app_command_deploy }}

      ---------------------------------
      inventory_hostname: {{ inventory_hostname }}
      nodename: {{ ansible_facts.nodename }}
      ansible_default_ipv4.address: {{ ansible_default_ipv4.address }}


#      devshop_app_git_root: {{ devshop_app_git_root }}
#      devshop_app_host: {{ devshop_app_host }}
#      ---------------------------------
#      devshop_app_servers:
#      {{ devshop_app_servers | to_nice_yaml }}
#      ---------------------------------
#      inventory_hostname: {{ inventory_hostname }}
#      ansible_host: {{ ansible_host }}
#      ansible_connection: {{ ansible_connection }}
#      nodename: {{ ansible_facts.nodename }}
#      ansible_default_ipv4.address: {{ ansible_default_ipv4.address }}
#
#      groups:
#      {{ group_names | to_nice_yaml }}
#
#      devshop_service_db_user: {{ devshop_service_db_user }}
#      devshop_service_db_name: {{ devshop_service_db_name }}
#      devshop_service_db_host: {{ devshop_service_db_host }}

- name: Prepare Parent Directory
  file:
    path: "{{ devshop_app_git_root }}"
    state: directory
    owner: "{{ devshop_app_user }}"
    group: "{{ devshop_app_user_group }}"
    mode: '0755'

- name: Prepare app source code.
  become: yes
  become_user: "{{ devshop_app_user }}"
  git:
    repo: "{{ devshop_app_git_repository }}"
    version: "{{ devshop_app_git_reference }}"
    dest: "{{ devshop_app_git_root }}"
    accept_hostkey: yes
    force: "{{ devshop_app_git_force }}"

  register: git_results
  notify:
    - run build
    - run deploy

- name: Forced build requested.
  when:
    - force_build
    - git_results.changed == false
  command: "echo Forcing git handlers, force_build variable was set."
  notify:
    - run build
    - run deploy

- name: Git Clone and Checkout Complete!
  debug:
    msg: "{{ git_results }}"

- name: Trigger Git Handlers before moving on.
  meta: flush_handlers

- name: Save command results
  set_fact:
    devshop_app_results:
      build:
        exit: "{{ app_build_results.rc | default('n/a') }}"
        output: "{{ app_build_results.stdout | default('') }}"

      deploy:
        exit: "{{ app_deploy_results.rc | default('n/a') }}"
        output: "{{ app_deploy_results.stdout | default('') }}"

- name: devshop.app build results
  when: devshop_app_results is defined
  failed_when:
    - (app_build_results is defined and app_build_results.rc != 0) or
      (app_deploy_results is defined and app_build_results.rc != 0)
  debug:
    msg: |
      {{ devshop_app_results | to_nice_yaml }}