---
# handlers file for devshop.app

- name: run build
  shell:
    cmd: "{{ devshop_app_commands.build }} 2>&1"
    chdir: "{{ devshop_app_git_root }}"
  become: yes
  become_user: "{{ devshop_app_user }}"
  when: devshop_app_commands.build is defined
  register: app_build_results
  ignore_errors: yes

- name: run deploy
  shell:
    cmd: "{{ devshop_app_commands.deploy }} 2>&1"
    chdir: "{{ devshop_app_git_root }}"
  become: yes
  become_user: "{{ devshop_app_user }}"
  when: devshop_app_commands.deploy is defined
  register: app_deploy_results
  ignore_errors: yes
