---

# Control User
# The user that clones the platform code and runs ansible-playbook.
# Has root access to hosts on the platform.
devshop_control_user: "{{ ansible_user | default(ansible_env.SUDO_USER) | default(ansible_env.USER, true) | default(ansible_user_id, true) }}"
devshop_control_user_home: "{{ ansible_env.HOME | default(ansible_user_dir, true) }}"

# Platform User
# The user that clones app code and runs app commands.
# Does not have root access anywhere.
devshop_platform_user: "platform"
devshop_platform_user_home: "/var/platform"
devshop_platform_user_generate_ssh_key: yes
devshop_platform_user_group: "{{ devshop_platform_user }}"
devshop_platform_user_comment: "The DevShop Platform User"
devshop_platform_user_shell: "/bin/bash"

# Set if needed.
# See https://docs.ansible.com/ansible/latest/collections/ansible/posix/user_module.html
# devshop_platform_user_uid: 1001
# devshop_platform_user_gid: 1001
# devshop_platform_user_comment: "The DevShop Platform User"
# devshop_platform_user_ssh_key_bits: 2048
# devshop_platform_user_ssh_key_file: .ssh/id_rsa

devshop_host_prepare_task_files:
  - 'host.yml'
  - 'packages.yml'
  - 'users.yml'

# Passed to App Hosts as devshop_app_user.
devshop_host_app_user: "{{ devshop_platform_user }}"
devshop_host_app_user_group: "{{ devshop_platform_user_group }}"
devshop_host_apps_root: "{{ devshop_platform_user_home }}/apps"

devshop_host_roles: []
devshop_host_services: []

devshop_app_git_document_root: web

# Set to "latest" to update packages
devshop_host_common_packages_state: present

# The default docker image to use when creating Servers.
devshop_host_docker_image: geerlingguy/docker-ubuntu1804-ansible

# The docker command to use when creating the container.
# If blank, the default command from the container will be used.
devshop_host_docker_command: ""

# The docker volumes to use when creating the container.
# If overriding, be sure to include these volumes if needed.
devshop_host_docker_volumes:
  - "/sys/fs/cgroup:/sys/fs/cgroup:ro"

# The docker ports to use when creating the container.
# If overriding, be sure to include these volumes if needed.
devshop_host_docker_published_ports:
  - "2222:22"

# Docker labels to apply to this container server.
devshop_host_docker_labels: {}

# Server hostname will default to this unless overridden in your inventory or extra_vars.
# devshop_host_hostname: "{{ inventory_hostname }}"
devshop_host_hostname_ignore_errors: true
