---

- name: Server Hosts Config
  when:
    - '"servers" in group_names'
    - '"http" in group_names'

  block:
    - name: "Preparing DevShop Service: http"
      debug:
        msg: |
          Current Host: {{ inventory_hostname }}

    - name: "All app hosts that use this server:"
      debug:
        msg: |
          {{ hostvars[item] }}
      with_items: "{{ groups['apps'] }}"
      when:
      - "{{ 'devshop_app_server_http' in hostvars[item] }}"
      - hostvars[item]['devshop_app_server_http'] == inventory_hostname

    # See https://github.com/geerlingguy/ansible-role-apache#requirements
    - name: "Prepare Certificates folder"
      with_items: "{{ groups['apps'] }}"
      when:
        - "{{ 'devshop_app_server_http' in hostvars[item] }}"
        - hostvars[item]['devshop_app_server_http'] == inventory_hostname
      file:
        path: "{{ hostvars[item]['devshop_app_http_certificates_root'] }}"
        state: directory
        owner: "{{ hostvars[item]['devshop_app_http_certificates_root_owner'] | default(devshop_platform_user) }}"
        group: "{{ hostvars[item]['devshop_app_http_certificates_root_group'] | default(devshop_platform_user) }}"
        mode: "{{ hostvars[item]['devshop_app_http_certificates_root_mode'] | default(omit) }}"

    - name: "Generate self-signed certs"
      with_items: "{{ groups['apps'] }}"
      when:
        - "{{ 'devshop_app_server_http' in hostvars[item] }}"
        - hostvars[item]['devshop_app_server_http'] == inventory_hostname
      command: "{{ hostvars[item]['devshop_app_http_certificate_generate_command'] }}"
      become: true
      become_user: "{{ devshop_platform_user }}"

    # @TODO: Move lookup of apps using this server to server_vars.py
    - name: "Prepare Apache VHosts."
      with_items: "{{ groups['apps'] }}"
      when:
        - "{{ 'devshop_app_server_http' in hostvars[item] }}"
        - hostvars[item]['devshop_app_server_http'] == inventory_hostname
      set_fact:
        devshop_app_apache_vhost:

          # See https://github.com/geerlingguy/ansible-role-apache
          servername: "{{ item }}"

          # NOTE: hostvars are from inventory. They do NOT include app role defaults.
          documentroot: "{{ hostvars[item]['devshop_app_git_root'] }}/{{ hostvars[item]['devshop_app_git_document_root'] | default(devshop_app_git_document_root) }}"
          extra_parameters: |
            {% if 'devshop_app_domains' in hostvars[item]: %}
              {% for domain in hostvars[item]['devshop_app_domains'] %}
            ServerAlias {{ domain }}
              {% endfor %}
            {% endif %}
          certificate_file: "{{ hostvars[item]['devshop_app_http_certificate_file'] | default(omit) }}"
          certificate_key_file: "{{ hostvars[item]['devshop_app_http_certificate_key_file'] | default(omit) }}"
          certificate_chain_file: "{{ hostvars[item]['devshop_app_http_certificate_chain_file'] | default(omit) }}"

      register: apache_vhost_register

    - name: "Prepare Certbot Variables"
      with_items: "{{ groups['apps'] }}"
      when:
        - "{{ 'devshop_app_server_http' in hostvars[item] }}"
        - hostvars[item]['devshop_app_server_http'] == inventory_hostname

      register: certbot_certs_register
      set_fact:
        devshop_app_certbot_cert:
          enable: "{{ hostvars[item]['devshop_app_server_http_letsencrypt'] | default(omit) }}"
          webroot: "{{ hostvars[item]['devshop_app_git_root'] + '/' + hostvars[item]['devshop_app_git_document_root'] | default(omit) }}"
          domains: "{{ [item, hostvars[item]['devshop_app_domains'] | default([])] | flatten | default(omit)}}"

          # See https://github.com/geerlingguy/ansible-role-certbot:
          # @TODO: Allow per site cert emails?
          # email:
          # - email: janedoe@example.com
          #   webroot: "/var/www/html"
          #   domains:
          #     - example1.com
          #     - example2.com
          # - domains:
          #     - example3.com:

    - debug:
        msg: "{{ certbot_certs_register.results | selectattr('ansible_facts') }}"

    - name: "Set Facts for host."
      set_fact:
        apache_vhosts: "{{ apache_vhost_register.results | map(attribute='ansible_facts.devshop_app_apache_vhost') | list }}"
        apache_vhosts_ssl: "{{ apache_vhost_register.results | map(attribute='ansible_facts.devshop_app_apache_vhost') | list }}"

        # Override role defaults with service defaults.
        apache_mods_enabled: "{{ devshop_service_http_apache_mods_enabled | list }}"

        certbot_certs: "{{ certbot_certs_register.results | map(attribute='ansible_facts.devshop_app_certbot_cert') | selectattr('enable') | list}}"

        # Generating certs during server playbook run isn't great. Too many and LE will lock you out.
        certbot_create_if_missing: no

        certbot_create_standalone_stop_services: []
        certbot_auto_renew_user: "{{ devshop_platform_user }}"
        certbot_auto_renew_hour: "3"
        certbot_auto_renew_minute: "30"
        certbot_create_method: "webroot"

    - name: "Set Facts for Debian hosts."
      set_fact:
        php_packages_extra:
          - "libapache2-mod-php{{ php_version }}"
      when:
        - ansible_os_family == 'Debian'


    - name: "Variables prepared."
      debug:
        msg: |
          Current Host: {{ inventory_hostname }}
          apache_vhosts: {{ apache_vhosts }}
          apache_mods_enabled: {{ apache_mods_enabled }}
          certbot_certs: {{ certbot_certs }}
