---

- name: Server Hosts Config
  when:
    - '"servers" in group_names'
    - '"http" in group_names'

  block:
    - name: "Preparing DevShop Service: http"
      debug:
        msg: |
          Current Host: {{ inventory_hostname }}

    - name: "All app hosts that use this server:"
      debug:
        msg: |
          {{ hostvars[item] }}
      with_items: "{{ groups['apps'] }}"
      when: hostvars[item]['devshop_app_server_http'] == inventory_hostname


    # See https://github.com/geerlingguy/ansible-role-apache#requirements
    - name: "Prepare Certificates folder"
      with_items: "{{ groups['apps'] }}"
      when: hostvars[item]['devshop_app_server_http'] == inventory_hostname
      file:
        path: "{{ hostvars[item]['devshop_app_http_certificates_root'] }}"
        state: directory
        owner: "{{ hostvars[item]['devshop_app_http_certificates_root_owner'] | default(devshop_platform_user) }}"
        group: "{{ hostvars[item]['devshop_app_http_certificates_root_group'] | default(devshop_platform_user) }}"
        mode: "{{ hostvars[item]['devshop_app_http_certificates_root_mode'] | default(omit) }}"

    - name: "Generate self-signed certs"
      with_items: "{{ groups['apps'] }}"
      when: hostvars[item]['devshop_app_server_http'] == inventory_hostname
      command: "{{ hostvars[item]['devshop_app_http_certificate_generate_command'] }}"
      become: true
      become_user: "{{ devshop_platform_user }}"

    # @TODO: Move lookup of apps using this server to server_vars.py
    - name: "Prepare Apache VHosts."
      with_items: "{{ groups['apps'] }}"
      when: hostvars[item]['devshop_app_server_http'] == inventory_hostname
      set_fact:
        devshop_app_apache_vhost:

          # See https://github.com/geerlingguy/ansible-role-apache
          servername: "{{ item }}"

          # NOTE: hostvars are from inventory. They do NOT include app role defaults.
          documentroot: "{{ hostvars[item]['devshop_app_git_root'] }}/{{ hostvars[item]['devshop_app_git_document_root'] | default(devshop_app_git_document_root) }}"
          extra_parameters: |
            {% if 'devshop_app_domains' in hostvars[item]: %}
              {% for domain in hostvars[item]['devshop_app_domains'] %}
            ServerAlias {{ domain }}
              {% endfor %}
            {% endif %}
          certificate_file: "{{ hostvars[item]['devshop_app_http_certificate_file'] | default(omit) }}"
          certificate_key_file: "{{ hostvars[item]['devshop_app_http_certificate_key_file'] | default(omit) }}"
          certificate_chain_file: "{{ hostvars[item]['devshop_app_http_certificate_chain_file'] | default(omit) }}"

      register: apache_vhost_register

    - name: "Set Facts for host."
      set_fact:
        apache_vhosts: "{{ apache_vhost_register.results | map(attribute='ansible_facts.devshop_app_apache_vhost') | list }}"
        apache_vhosts_ssl: "{{ apache_vhost_register.results | map(attribute='ansible_facts.devshop_app_apache_vhost') | list }}"

        # Override role defaults with service defaults.
        apache_mods_enabled: "{{ devshop_service_http_apache_mods_enabled | list }}"


    - name: "Set Facts for Debian hosts."
      set_fact:
        php_packages_extra:
          - "libapache2-mod-php{{ php_version }}"
      when:
        - ansible_os_family == 'Debian'


    - name: "Variables prepared."
      debug:
        msg: |
          Current Host: {{ inventory_hostname }}
          apache_vhosts: {{ apache_vhosts }}
          apache_mods_enabled: {{ apache_mods_enabled }}
