---

- name: Save Docker Container as Image
  debug:
    msg: | 
      Running command:
      command docker commit {{ inventory_hostname }} {{ devshop_host_docker_image }}

- name: Save Docker Container as Image
  local_action: command docker commit {{ inventory_hostname }} {{ devshop_host_docker_image }}
  when:
    - devshop_host_docker_image_commit_after_host_role
    - devshop_host_type is defined
    - devshop_host_type == "docker"
    - ansible_connection == "docker"

- name: DevShop.Services Role Complete.
  debug:
    msg: |
      ------------------------------------------
      devshop.services role complete.
      All role dependencies installed.

      inventory_hostname: {{ inventory_hostname }}
      nodename: {{ ansible_facts.nodename }}
      ansible_default_ipv4.address: {{ ansible_default_ipv4.address }}

      groups:
      {{ group_names | to_nice_yaml }}

      devshop_host_roles:
      {{ devshop_host_roles | default('None') | to_nice_yaml }}
